name: Check For RobotPy Updates

on:
  schedule:
    # In UTC this is 7am EST
    - cron: "0 12 * * *"

jobs:
  check-robot-py:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps -r requirements.txt
          ./scripts/check-for-pip-updates.sh
